services:
  minetest:
    build: .
    container_name: minetest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - CLI_ARGS=--worldname TheWorld --port 30000 #optional
    volumes:
      - ./minetest/worlds:/config/.minetest/worlds
    ports:
      - 30000:30000/udp
    restart: unless-stopped
